pipeline {
    agent any

    stages {
        stage('Base') {
            steps {
                sh 'echo \'Hi I am Base\''
            }
        }
    }
}
//
// node('Jenkins') {
//     stage('Base') {
//         steps {
//             sh 'echo \'Hi I am Base\''
//         }
//     }
// }
