// pipeline {
//     agent any
//
//     stages {
//         stage('Base') {
//             steps {
//                 sh 'echo \'Hi I am Base\''
//             }
//         }
//     }
// }

pipeline{
    agent none
    stages {
        stage('Base') {
            steps {
                sh 'echo \'Hi I am Base\''
            }
        }
    }
}
